# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, parsec, shelly, tasty, tastyHunit, text }:

cabal.mkDerivation (self: {
  pname = "cabal-edit";
  version = "0.1";
  src = ./.;
  isLibrary = true;
  isExecutable = true;
  buildDepends = [ parsec shelly text ];
  testDepends = [ parsec tasty tastyHunit text ];
  meta = {
    description = "Library for automated edits to .cabal files";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
